
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /

# copy csproj and restore as distinct layers
COPY ./src/Scraper/Scraper.csproj ./Scraper/
RUN dotnet restore ./Scraper/Scraper.csproj

# copy everything else and build app
COPY ./src/Scraper/ ./Scraper/

WORKDIR /Scraper
RUN dotnet publish -c Release  -o out

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /
COPY --from=build ./Scraper/out .

ENV ASPNETCORE_ENVIRONMENT docker

ENTRYPOINT ["dotnet", "Scraper.dll"]