
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /

# copy csproj and restore as distinct layers
COPY ./src/Cards/Cards.csproj ./Cards/
RUN dotnet restore ./Cards/Cards.csproj

# copy everything else and build app
COPY ./src/Cards/ ./Cards/

WORKDIR /Cards
RUN dotnet publish -c Release  -o out

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /
COPY --from=build ./Cards/out .

ENV ASPNETCORE_ENVIRONMENT docker

ENTRYPOINT ["dotnet", "Cards.dll"]