
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /

# copy csproj and restore as distinct layers
COPY ./src/PriceChecker/PriceChecker.csproj ./PriceChecker/
RUN dotnet restore ./PriceChecker/PriceChecker.csproj

# copy everything else and build app
COPY ./src/PriceChecker/ ./PriceChecker/

WORKDIR /PriceChecker
RUN dotnet publish -c Release  -o out

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /
COPY --from=build ./PriceChecker/out .

ENV ASPNETCORE_ENVIRONMENT docker

ENTRYPOINT ["dotnet", "PriceChecker.dll"]